//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostCode_Detail
    {
        public decimal CC_ID { get; set; }
        public string CC_Name { get; set; }
        public Nullable<decimal> Prj_ID { get; set; }
        public Nullable<System.DateTime> RequestedDate { get; set; }
        public Nullable<decimal> BudgetAmount { get; set; }
        public Nullable<byte> TypeofPrj { get; set; }
        public Nullable<int> PrjPlatform { get; set; }
        public string PrjPlatformids { get; set; }
    }
}
