//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProjectManagementSystemEntities : DbContext
    {
        public ProjectManagementSystemEntities()
            : base("name=ProjectManagementSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CostCode_Detail> CostCode_Detail { get; set; }
        public virtual DbSet<CostCodePrjDetail> CostCodePrjDetails { get; set; }
        public virtual DbSet<PrjPlatform> PrjPlatforms { get; set; }
        public virtual DbSet<Project_Detail> Project_Detail { get; set; }
        public virtual DbSet<TypeofPrj> TypeofPrjs { get; set; }
    }
}
