//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    

    public partial class PrjPlatform
    {
        public int PrjPltfrmID { get; set; }
        public string PrjPltfrmName { get; set; }
        public Nullable<byte> IsSelected { get; set; }
    }
}
