//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project_Detail
    {
        public decimal Prj_ID { get; set; }
        public string Prj_Name { get; set; }
        public Nullable<System.DateTime> Date_Of_Creation { get; set; }
    }
}
